### ISSUE TITLE
CMakeLists.txt minimum cmake version

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/H4I-MKLShim#7]
Is there a reason we need to set the minimum cmake version to 3.24 (i.e. https://github.com/CHIP-SPV/H4I-MKLShim/blob/4b9a4a27b51cc5608fa0cb4c410101f2e97f0492/CMakeLists.txt#L4)? That is, is there a feature in 3.24 that is needed? Otherwise, could we change it to 3.23 or something lower depending on the needs? Just personally, 3.23 has been working fine. I can install 3.24 but if we don't need it to be 3.24 I'd rather just downgrade it so people don't get unnecessary errors.

(And the same for the other H4I-* repos!)

Thanks!

**Comment by rothpc** [comment]
Closed with version 0.1.0.
